window.App = window.App || {};

// Localized topic/category names (e.g. "Greetings", "Family"), independent from
// which language is being studied — these are course-structure labels shown in
// the current INTERFACE language. The 34 keys through "music" are shared by all
// 22 learnable languages; the remaining 15 (law_society..clothing2) exist only
// in the Czech course (which has extra topics beyond the other 21 languages).
App.CATEGORY_NAMES = {
  ru: {
    greetings: 'Приветствия', numbers: 'Числа', family: 'Семья', food: 'Еда', travel: 'Путешествия',
    colors: 'Цвета', time: 'Дни и время', verbs: 'Глаголы и прилагательные', body: 'Тело', clothing: 'Одежда',
    weather: 'Погода', work: 'Работа и профессии', emotions: 'Эмоции и чувства', house: 'Дом и быт', transport: 'Транспорт',
    places: 'Город и места', shopping: 'Покупки и магазины', technology: 'Технологии', sport: 'Спорт и хобби', nature: 'Природа и животные',
    health: 'Здоровье и медицина', education: 'Образование', finance: 'Деньги и финансы', restaurant: 'В ресторане',
    daily: 'Распорядок дня', communication: 'Общение и связь', celebrations: 'Праздники и торжества', countries: 'Страны и национальности',
    seasons: 'Времена года и календарь', adjectives: 'Прилагательные и противоположности', verbs2: 'Дополнительные глаголы',
    kitchen: 'Кухня и готовка', materials: 'Материалы и инструменты', music: 'Музыка и искусство',
    law_society: 'Общество и право', geography: 'География и природа', numbers2: 'Числа и математика', character: 'Черты характера',
    body2: 'Тело и внешность (продолжение)', animals2: 'Дополнительные животные', professions2: 'Дополнительные профессии',
    house2: 'Дом (продолжение)', school2: 'Школа (продолжение)', travel2: 'Путешествия (продолжение)', environment: 'Погода и экология',
    shapes: 'Формы и измерения', computer2: 'Компьютеры (продолжение)', religion: 'Религия и духовность', clothing2: 'Одежда (продолжение)'
  },
  en: {
    greetings: 'Greetings', numbers: 'Numbers', family: 'Family', food: 'Food', travel: 'Travel',
    colors: 'Colors', time: 'Days & Time', verbs: 'Verbs & Adjectives', body: 'Body', clothing: 'Clothing',
    weather: 'Weather', work: 'Work & Professions', emotions: 'Emotions & Feelings', house: 'Home & Household', transport: 'Transport',
    places: 'City & Places', shopping: 'Shopping & Stores', technology: 'Technology', sport: 'Sports & Hobbies', nature: 'Nature & Animals',
    health: 'Health & Medicine', education: 'Education', finance: 'Money & Finance', restaurant: 'At the Restaurant',
    daily: 'Daily Routine', communication: 'Communication', celebrations: 'Holidays & Celebrations', countries: 'Countries & Nationalities',
    seasons: 'Seasons & Calendar', adjectives: 'Adjectives & Opposites', verbs2: 'More Verbs',
    kitchen: 'Kitchen & Cooking', materials: 'Materials & Tools', music: 'Music & Art',
    law_society: 'Society & Law', geography: 'Geography & Nature', numbers2: 'Numbers & Math', character: 'Character Traits',
    body2: 'Body & Appearance (More)', animals2: 'More Animals', professions2: 'More Professions',
    house2: 'Home (More)', school2: 'School (More)', travel2: 'Travel (More)', environment: 'Weather & Environment',
    shapes: 'Shapes & Measurements', computer2: 'Computers (More)', religion: 'Religion & Spirituality', clothing2: 'Clothing (More)'
  },
  pl: {
    greetings: 'Powitania', numbers: 'Liczby', family: 'Rodzina', food: 'Jedzenie', travel: 'Podróże',
    colors: 'Kolory', time: 'Dni i czas', verbs: 'Czasowniki i przymiotniki', body: 'Ciało', clothing: 'Ubrania',
    weather: 'Pogoda', work: 'Praca i zawody', emotions: 'Emocje i uczucia', house: 'Dom i gospodarstwo domowe', transport: 'Transport',
    places: 'Miasto i miejsca', shopping: 'Zakupy i sklepy', technology: 'Technologia', sport: 'Sport i hobby', nature: 'Przyroda i zwierzęta',
    health: 'Zdrowie i medycyna', education: 'Edukacja', finance: 'Pieniądze i finanse', restaurant: 'W restauracji',
    daily: 'Rozkład dnia', communication: 'Komunikacja', celebrations: 'Święta i uroczystości', countries: 'Kraje i narodowości',
    seasons: 'Pory roku i kalendarz', adjectives: 'Przymiotniki i przeciwieństwa', verbs2: 'Więcej czasowników',
    kitchen: 'Kuchnia i gotowanie', materials: 'Materiały i narzędzia', music: 'Muzyka i sztuka',
    law_society: 'Społeczeństwo i prawo', geography: 'Geografia i przyroda', numbers2: 'Liczby i matematyka', character: 'Cechy charakteru',
    body2: 'Ciało i wygląd (ciąg dalszy)', animals2: 'Więcej zwierząt', professions2: 'Więcej zawodów',
    house2: 'Dom (ciąg dalszy)', school2: 'Szkoła (ciąg dalszy)', travel2: 'Podróże (ciąg dalszy)', environment: 'Pogoda i środowisko',
    shapes: 'Kształty i miary', computer2: 'Komputery (ciąg dalszy)', religion: 'Religia i duchowość', clothing2: 'Ubrania (ciąg dalszy)'
  },
  cs: {
    greetings: 'Pozdravy', numbers: 'Čísla', family: 'Rodina', food: 'Jídlo', travel: 'Cestování',
    colors: 'Barvy', time: 'Dny a čas', verbs: 'Slovesa a přídavná jména', body: 'Tělo', clothing: 'Oblečení',
    weather: 'Počasí', work: 'Práce a povolání', emotions: 'Emoce a pocity', house: 'Dům a domácnost', transport: 'Doprava',
    places: 'Město a místa', shopping: 'Nakupování a obchody', technology: 'Technologie', sport: 'Sport a koníčky', nature: 'Příroda a zvířata',
    health: 'Zdraví a medicína', education: 'Vzdělání', finance: 'Peníze a finance', restaurant: 'V restauraci',
    daily: 'Denní rutina', communication: 'Komunikace', celebrations: 'Svátky a oslavy', countries: 'Země a národnosti',
    seasons: 'Roční období a kalendář', adjectives: 'Přídavná jména a protiklady', verbs2: 'Další slovesa',
    kitchen: 'Kuchyně a vaření', materials: 'Materiály a nástroje', music: 'Hudba a umění',
    law_society: 'Společnost a právo', geography: 'Geografie a příroda', numbers2: 'Čísla a matematika', character: 'Povahové rysy',
    body2: 'Tělo a vzhled (pokračování)', animals2: 'Další zvířata', professions2: 'Další povolání',
    house2: 'Dům (pokračování)', school2: 'Škola (pokračování)', travel2: 'Cestování (pokračování)', environment: 'Počasí a životní prostředí',
    shapes: 'Tvary a míry', computer2: 'Počítače (pokračování)', religion: 'Náboženství a duchovno', clothing2: 'Oblečení (pokračování)'
  },
  sk: {
    greetings: 'Pozdravy', numbers: 'Čísla', family: 'Rodina', food: 'Jedlo', travel: 'Cestovanie',
    colors: 'Farby', time: 'Dni a čas', verbs: 'Slovesá a prídavné mená', body: 'Telo', clothing: 'Oblečenie',
    weather: 'Počasie', work: 'Práca a povolania', emotions: 'Emócie a pocity', house: 'Dom a domácnosť', transport: 'Doprava',
    places: 'Mesto a miesta', shopping: 'Nakupovanie a obchody', technology: 'Technológie', sport: 'Šport a koníčky', nature: 'Príroda a zvieratá',
    health: 'Zdravie a medicína', education: 'Vzdelanie', finance: 'Peniaze a financie', restaurant: 'V reštaurácii',
    daily: 'Denný režim', communication: 'Komunikácia', celebrations: 'Sviatky a oslavy', countries: 'Krajiny a národnosti',
    seasons: 'Ročné obdobia a kalendár', adjectives: 'Prídavné mená a protiklady', verbs2: 'Ďalšie slovesá',
    kitchen: 'Kuchyňa a varenie', materials: 'Materiály a nástroje', music: 'Hudba a umenie',
    law_society: 'Spoločnosť a právo', geography: 'Geografia a príroda', numbers2: 'Čísla a matematika', character: 'Povahové vlastnosti',
    body2: 'Telo a vzhľad (pokračovanie)', animals2: 'Ďalšie zvieratá', professions2: 'Ďalšie povolania',
    house2: 'Dom (pokračovanie)', school2: 'Škola (pokračovanie)', travel2: 'Cestovanie (pokračovanie)', environment: 'Počasie a životné prostredie',
    shapes: 'Tvary a miery', computer2: 'Počítače (pokračovanie)', religion: 'Náboženstvo a duchovno', clothing2: 'Oblečenie (pokračovanie)'
  },
  uk: {
    greetings: 'Привітання', numbers: 'Числа', family: 'Сім’я', food: 'Їжа', travel: 'Подорожі',
    colors: 'Кольори', time: 'Дні та час', verbs: 'Дієслова та прикметники', body: 'Тіло', clothing: 'Одяг',
    weather: 'Погода', work: 'Робота та професії', emotions: 'Емоції та почуття', house: 'Дім і побут', transport: 'Транспорт',
    places: 'Місто та місця', shopping: 'Покупки та магазини', technology: 'Технології', sport: 'Спорт і хобі', nature: 'Природа і тварини',
    health: 'Здоров’я та медицина', education: 'Освіта', finance: 'Гроші та фінанси', restaurant: 'У ресторані',
    daily: 'Розпорядок дня', communication: 'Спілкування', celebrations: 'Свята і урочистості', countries: 'Країни і національності',
    seasons: 'Пори року і календар', adjectives: 'Прикметники і протилежності', verbs2: 'Додаткові дієслова',
    kitchen: 'Кухня і готування', materials: 'Матеріали та інструменти', music: 'Музика і мистецтво',
    law_society: 'Суспільство і право', geography: 'Географія і природа', numbers2: 'Числа і математика', character: 'Риси характеру',
    body2: 'Тіло і зовнішність (продовження)', animals2: 'Додаткові тварини', professions2: 'Додаткові професії',
    house2: 'Дім (продовження)', school2: 'Школа (продовження)', travel2: 'Подорожі (продовження)', environment: 'Погода і екологія',
    shapes: 'Форми і виміри', computer2: 'Комп’ютери (продовження)', religion: 'Релігія і духовність', clothing2: 'Одяг (продовження)'
  },
  bg: {
    greetings: 'Поздрави', numbers: 'Числа', family: 'Семейство', food: 'Храна', travel: 'Пътувания',
    colors: 'Цветове', time: 'Дни и време', verbs: 'Глаголи и прилагателни', body: 'Тяло', clothing: 'Дрехи',
    weather: 'Времето', work: 'Работа и професии', emotions: 'Емоции и чувства', house: 'Дом и бит', transport: 'Транспорт',
    places: 'Град и места', shopping: 'Пазаруване и магазини', technology: 'Технологии', sport: 'Спорт и хобита', nature: 'Природа и животни',
    health: 'Здраве и медицина', education: 'Образование', finance: 'Пари и финанси', restaurant: 'В ресторанта',
    daily: 'Дневен режим', communication: 'Общуване', celebrations: 'Празници и тържества', countries: 'Държави и националности',
    seasons: 'Сезони и календар', adjectives: 'Прилагателни и противоположности', verbs2: 'Още глаголи',
    kitchen: 'Кухня и готвене', materials: 'Материали и инструменти', music: 'Музика и изкуство',
    law_society: 'Общество и право', geography: 'География и природа', numbers2: 'Числа и математика', character: 'Черти на характера',
    body2: 'Тяло и външност (продължение)', animals2: 'Още животни', professions2: 'Още професии',
    house2: 'Дом (продължение)', school2: 'Училище (продължение)', travel2: 'Пътувания (продължение)', environment: 'Времето и екологията',
    shapes: 'Форми и размери', computer2: 'Компютри (продължение)', religion: 'Религия и духовност', clothing2: 'Дрехи (продължение)'
  },
  fr: {
    greetings: 'Salutations', numbers: 'Nombres', family: 'Famille', food: 'Nourriture', travel: 'Voyage',
    colors: 'Couleurs', time: 'Jours et heure', verbs: 'Verbes et adjectifs', body: 'Corps', clothing: 'Vêtements',
    weather: 'Météo', work: 'Travail et métiers', emotions: 'Émotions et sentiments', house: 'Maison et foyer', transport: 'Transports',
    places: 'Ville et lieux', shopping: 'Achats et magasins', technology: 'Technologie', sport: 'Sports et loisirs', nature: 'Nature et animaux',
    health: 'Santé et médecine', education: 'Éducation', finance: 'Argent et finances', restaurant: 'Au restaurant',
    daily: 'Routine quotidienne', communication: 'Communication', celebrations: 'Fêtes et célébrations', countries: 'Pays et nationalités',
    seasons: 'Saisons et calendrier', adjectives: 'Adjectifs et contraires', verbs2: 'Verbes supplémentaires',
    kitchen: 'Cuisine et préparation', materials: 'Matériaux et outils', music: 'Musique et art',
    law_society: 'Société et droit', geography: 'Géographie et nature', numbers2: 'Nombres et mathématiques', character: 'Traits de caractère',
    body2: 'Corps et apparence (suite)', animals2: 'Animaux supplémentaires', professions2: 'Métiers supplémentaires',
    house2: 'Maison (suite)', school2: 'École (suite)', travel2: 'Voyage (suite)', environment: 'Météo et environnement',
    shapes: 'Formes et mesures', computer2: 'Ordinateurs (suite)', religion: 'Religion et spiritualité', clothing2: 'Vêtements (suite)'
  },
  es: {
    greetings: 'Saludos', numbers: 'Números', family: 'Familia', food: 'Comida', travel: 'Viajes',
    colors: 'Colores', time: 'Días y hora', verbs: 'Verbos y adjetivos', body: 'Cuerpo', clothing: 'Ropa',
    weather: 'Clima', work: 'Trabajo y profesiones', emotions: 'Emociones y sentimientos', house: 'Casa y hogar', transport: 'Transporte',
    places: 'Ciudad y lugares', shopping: 'Compras y tiendas', technology: 'Tecnología', sport: 'Deportes y aficiones', nature: 'Naturaleza y animales',
    health: 'Salud y medicina', education: 'Educación', finance: 'Dinero y finanzas', restaurant: 'En el restaurante',
    daily: 'Rutina diaria', communication: 'Comunicación', celebrations: 'Fiestas y celebraciones', countries: 'Países y nacionalidades',
    seasons: 'Estaciones y calendario', adjectives: 'Adjetivos y opuestos', verbs2: 'Más verbos',
    kitchen: 'Cocina y preparación', materials: 'Materiales y herramientas', music: 'Música y arte',
    law_society: 'Sociedad y derecho', geography: 'Geografía y naturaleza', numbers2: 'Números y matemáticas', character: 'Rasgos de carácter',
    body2: 'Cuerpo y apariencia (más)', animals2: 'Más animales', professions2: 'Más profesiones',
    house2: 'Casa (más)', school2: 'Escuela (más)', travel2: 'Viajes (más)', environment: 'Clima y medio ambiente',
    shapes: 'Formas y medidas', computer2: 'Computadoras (más)', religion: 'Religión y espiritualidad', clothing2: 'Ropa (más)'
  },
  it: {
    greetings: 'Saluti', numbers: 'Numeri', family: 'Famiglia', food: 'Cibo', travel: 'Viaggi',
    colors: 'Colori', time: 'Giorni e orari', verbs: 'Verbi e aggettivi', body: 'Corpo', clothing: 'Abbigliamento',
    weather: 'Meteo', work: 'Lavoro e professioni', emotions: 'Emozioni e sentimenti', house: 'Casa e vita domestica', transport: 'Trasporti',
    places: 'Città e luoghi', shopping: 'Acquisti e negozi', technology: 'Tecnologia', sport: 'Sport e hobby', nature: 'Natura e animali',
    health: 'Salute e medicina', education: 'Istruzione', finance: 'Denaro e finanza', restaurant: 'Al ristorante',
    daily: 'Routine quotidiana', communication: 'Comunicazione', celebrations: 'Feste e celebrazioni', countries: 'Paesi e nazionalità',
    seasons: 'Stagioni e calendario', adjectives: 'Aggettivi e contrari', verbs2: 'Altri verbi',
    kitchen: 'Cucina e preparazione', materials: 'Materiali e attrezzi', music: 'Musica e arte',
    law_society: 'Società e diritto', geography: 'Geografia e natura', numbers2: 'Numeri e matematica', character: 'Tratti di carattere',
    body2: 'Corpo e aspetto (continua)', animals2: 'Altri animali', professions2: 'Altre professioni',
    house2: 'Casa (continua)', school2: 'Scuola (continua)', travel2: 'Viaggi (continua)', environment: 'Meteo e ambiente',
    shapes: 'Forme e misure', computer2: 'Computer (continua)', religion: 'Religione e spiritualità', clothing2: 'Abbigliamento (continua)'
  },
  pt: {
    greetings: 'Cumprimentos', numbers: 'Números', family: 'Família', food: 'Comida', travel: 'Viagens',
    colors: 'Cores', time: 'Dias e horas', verbs: 'Verbos e adjetivos', body: 'Corpo', clothing: 'Roupas',
    weather: 'Clima', work: 'Trabalho e profissões', emotions: 'Emoções e sentimentos', house: 'Casa e lar', transport: 'Transporte',
    places: 'Cidade e lugares', shopping: 'Compras e lojas', technology: 'Tecnologia', sport: 'Esportes e hobbies', nature: 'Natureza e animais',
    health: 'Saúde e medicina', education: 'Educação', finance: 'Dinheiro e finanças', restaurant: 'No restaurante',
    daily: 'Rotina diária', communication: 'Comunicação', celebrations: 'Feriados e celebrações', countries: 'Países e nacionalidades',
    seasons: 'Estações e calendário', adjectives: 'Adjetivos e opostos', verbs2: 'Mais verbos',
    kitchen: 'Cozinha e preparo', materials: 'Materiais e ferramentas', music: 'Música e arte',
    law_society: 'Sociedade e direito', geography: 'Geografia e natureza', numbers2: 'Números e matemática', character: 'Traços de personalidade',
    body2: 'Corpo e aparência (mais)', animals2: 'Mais animais', professions2: 'Mais profissões',
    house2: 'Casa (mais)', school2: 'Escola (mais)', travel2: 'Viagens (mais)', environment: 'Clima e meio ambiente',
    shapes: 'Formas e medidas', computer2: 'Computadores (mais)', religion: 'Religião e espiritualidade', clothing2: 'Roupas (mais)'
  },
  ro: {
    greetings: 'Salutări', numbers: 'Numere', family: 'Familie', food: 'Mâncare', travel: 'Călătorii',
    colors: 'Culori', time: 'Zile și timp', verbs: 'Verbe și adjective', body: 'Corp', clothing: 'Îmbrăcăminte',
    weather: 'Vreme', work: 'Muncă și profesii', emotions: 'Emoții și sentimente', house: 'Casă și gospodărie', transport: 'Transport',
    places: 'Oraș și locuri', shopping: 'Cumpărături și magazine', technology: 'Tehnologie', sport: 'Sport și hobby-uri', nature: 'Natură și animale',
    health: 'Sănătate și medicină', education: 'Educație', finance: 'Bani și finanțe', restaurant: 'La restaurant',
    daily: 'Rutina zilnică', communication: 'Comunicare', celebrations: 'Sărbători', countries: 'Țări și naționalități',
    seasons: 'Anotimpuri și calendar', adjectives: 'Adjective și antonime', verbs2: 'Verbe suplimentare',
    kitchen: 'Bucătărie și gătit', materials: 'Materiale și unelte', music: 'Muzică și artă',
    law_society: 'Societate și drept', geography: 'Geografie și natură', numbers2: 'Numere și matematică', character: 'Trăsături de caracter',
    body2: 'Corp și înfățișare (continuare)', animals2: 'Alte animale', professions2: 'Alte profesii',
    house2: 'Casă (continuare)', school2: 'Școală (continuare)', travel2: 'Călătorii (continuare)', environment: 'Vreme și mediu',
    shapes: 'Forme și măsurători', computer2: 'Calculatoare (continuare)', religion: 'Religie și spiritualitate', clothing2: 'Îmbrăcăminte (continuare)'
  },
  de: {
    greetings: 'Begrüßungen', numbers: 'Zahlen', family: 'Familie', food: 'Essen', travel: 'Reisen',
    colors: 'Farben', time: 'Tage & Uhrzeit', verbs: 'Verben & Adjektive', body: 'Körper', clothing: 'Kleidung',
    weather: 'Wetter', work: 'Arbeit & Berufe', emotions: 'Gefühle & Emotionen', house: 'Haus & Haushalt', transport: 'Verkehrsmittel',
    places: 'Stadt & Orte', shopping: 'Einkaufen & Geschäfte', technology: 'Technologie', sport: 'Sport & Hobbys', nature: 'Natur & Tiere',
    health: 'Gesundheit & Medizin', education: 'Bildung', finance: 'Geld & Finanzen', restaurant: 'Im Restaurant',
    daily: 'Tagesablauf', communication: 'Kommunikation', celebrations: 'Feiertage & Feste', countries: 'Länder & Nationalitäten',
    seasons: 'Jahreszeiten & Kalender', adjectives: 'Adjektive & Gegenteile', verbs2: 'Weitere Verben',
    kitchen: 'Küche & Kochen', materials: 'Materialien & Werkzeuge', music: 'Musik & Kunst',
    law_society: 'Gesellschaft & Recht', geography: 'Geografie & Natur', numbers2: 'Zahlen & Mathematik', character: 'Charaktereigenschaften',
    body2: 'Körper & Aussehen (Fortsetzung)', animals2: 'Weitere Tiere', professions2: 'Weitere Berufe',
    house2: 'Haus (Fortsetzung)', school2: 'Schule (Fortsetzung)', travel2: 'Reisen (Fortsetzung)', environment: 'Wetter & Umwelt',
    shapes: 'Formen & Maße', computer2: 'Computer (Fortsetzung)', religion: 'Religion & Spiritualität', clothing2: 'Kleidung (Fortsetzung)'
  },
  nl: {
    greetings: 'Begroetingen', numbers: 'Getallen', family: 'Familie', food: 'Eten', travel: 'Reizen',
    colors: 'Kleuren', time: 'Dagen & tijd', verbs: 'Werkwoorden & bijvoeglijke naamwoorden', body: 'Lichaam', clothing: 'Kleding',
    weather: 'Weer', work: 'Werk & beroepen', emotions: 'Emoties & gevoelens', house: 'Huis & huishouden', transport: 'Vervoer',
    places: 'Stad & plaatsen', shopping: 'Winkelen & winkels', technology: 'Technologie', sport: 'Sport & hobby\'s', nature: 'Natuur & dieren',
    health: 'Gezondheid & medisch', education: 'Onderwijs', finance: 'Geld & financiën', restaurant: 'In het restaurant',
    daily: 'Dagelijkse routine', communication: 'Communicatie', celebrations: 'Feestdagen & vieringen', countries: 'Landen & nationaliteiten',
    seasons: 'Seizoenen & kalender', adjectives: 'Bijvoeglijke naamwoorden & tegenstellingen', verbs2: 'Meer werkwoorden',
    kitchen: 'Keuken & koken', materials: 'Materialen & gereedschap', music: 'Muziek & kunst',
    law_society: 'Maatschappij & recht', geography: 'Aardrijkskunde & natuur', numbers2: 'Getallen & wiskunde', character: 'Karaktereigenschappen',
    body2: 'Lichaam & uiterlijk (vervolg)', animals2: 'Meer dieren', professions2: 'Meer beroepen',
    house2: 'Huis (vervolg)', school2: 'School (vervolg)', travel2: 'Reizen (vervolg)', environment: 'Weer & milieu',
    shapes: 'Vormen & afmetingen', computer2: 'Computers (vervolg)', religion: 'Religie & spiritualiteit', clothing2: 'Kleding (vervolg)'
  },
  sv: {
    greetings: 'Hälsningar', numbers: 'Siffror', family: 'Familj', food: 'Mat', travel: 'Resor',
    colors: 'Färger', time: 'Dagar & tid', verbs: 'Verb & adjektiv', body: 'Kropp', clothing: 'Kläder',
    weather: 'Väder', work: 'Arbete & yrken', emotions: 'Känslor & humör', house: 'Hem & hushåll', transport: 'Transport',
    places: 'Stad & platser', shopping: 'Shopping & butiker', technology: 'Teknik', sport: 'Sport & hobbyer', nature: 'Natur & djur',
    health: 'Hälsa & medicin', education: 'Utbildning', finance: 'Pengar & ekonomi', restaurant: 'På restaurangen',
    daily: 'Dagliga rutiner', communication: 'Kommunikation', celebrations: 'Högtider & firande', countries: 'Länder & nationaliteter',
    seasons: 'Årstider & kalender', adjectives: 'Adjektiv & motsatser', verbs2: 'Fler verb',
    kitchen: 'Kök & matlagning', materials: 'Material & verktyg', music: 'Musik & konst',
    law_society: 'Samhälle & rätt', geography: 'Geografi & natur', numbers2: 'Siffror & matematik', character: 'Karaktärsdrag',
    body2: 'Kropp & utseende (fler)', animals2: 'Fler djur', professions2: 'Fler yrken',
    house2: 'Hem (fler)', school2: 'Skola (fler)', travel2: 'Resor (fler)', environment: 'Väder & miljö',
    shapes: 'Former & mått', computer2: 'Datorer (fler)', religion: 'Religion & andlighet', clothing2: 'Kläder (fler)'
  },
  no: {
    greetings: 'Hilsener', numbers: 'Tall', family: 'Familie', food: 'Mat', travel: 'Reiser',
    colors: 'Farger', time: 'Dager & tid', verbs: 'Verb & adjektiver', body: 'Kropp', clothing: 'Klær',
    weather: 'Vær', work: 'Arbeid & yrker', emotions: 'Følelser', house: 'Hjem & husholdning', transport: 'Transport',
    places: 'By & steder', shopping: 'Shopping & butikker', technology: 'Teknologi', sport: 'Sport & hobbyer', nature: 'Natur & dyr',
    health: 'Helse & medisin', education: 'Utdanning', finance: 'Penger & økonomi', restaurant: 'På restauranten',
    daily: 'Daglige rutiner', communication: 'Kommunikasjon', celebrations: 'Høytider & feiringer', countries: 'Land & nasjonaliteter',
    seasons: 'Årstider & kalender', adjectives: 'Adjektiver & motsetninger', verbs2: 'Flere verb',
    kitchen: 'Kjøkken & matlaging', materials: 'Materialer & verktøy', music: 'Musikk & kunst',
    law_society: 'Samfunn & jus', geography: 'Geografi & natur', numbers2: 'Tall & matematikk', character: 'Personlighetstrekk',
    body2: 'Kropp & utseende (mer)', animals2: 'Flere dyr', professions2: 'Flere yrker',
    house2: 'Hjem (mer)', school2: 'Skole (mer)', travel2: 'Reiser (mer)', environment: 'Vær & miljø',
    shapes: 'Former & mål', computer2: 'Datamaskiner (mer)', religion: 'Religion & spiritualitet', clothing2: 'Klær (mer)'
  },
  da: {
    greetings: 'Hilsener', numbers: 'Tal', family: 'Familie', food: 'Mad', travel: 'Rejser',
    colors: 'Farver', time: 'Dage & tid', verbs: 'Verber & adjektiver', body: 'Krop', clothing: 'Tøj',
    weather: 'Vejr', work: 'Arbejde & erhverv', emotions: 'Følelser', house: 'Hjem & husholdning', transport: 'Transport',
    places: 'By & steder', shopping: 'Indkøb & butikker', technology: 'Teknologi', sport: 'Sport & hobbyer', nature: 'Natur & dyr',
    health: 'Sundhed & medicin', education: 'Uddannelse', finance: 'Penge & økonomi', restaurant: 'På restauranten',
    daily: 'Daglig rutine', communication: 'Kommunikation', celebrations: 'Højtider & fejringer', countries: 'Lande & nationaliteter',
    seasons: 'Årstider & kalender', adjectives: 'Adjektiver & modsætninger', verbs2: 'Flere verber',
    kitchen: 'Køkken & madlavning', materials: 'Materialer & værktøj', music: 'Musik & kunst',
    law_society: 'Samfund & jura', geography: 'Geografi & natur', numbers2: 'Tal & matematik', character: 'Karaktertræk',
    body2: 'Krop & udseende (mere)', animals2: 'Flere dyr', professions2: 'Flere erhverv',
    house2: 'Hjem (mere)', school2: 'Skole (mere)', travel2: 'Rejser (mere)', environment: 'Vejr & miljø',
    shapes: 'Former & mål', computer2: 'Computere (mere)', religion: 'Religion & spiritualitet', clothing2: 'Tøj (mere)'
  },
  hr: {
    greetings: 'Pozdravi', numbers: 'Brojevi', family: 'Obitelj', food: 'Hrana', travel: 'Putovanja',
    colors: 'Boje', time: 'Dani i vrijeme', verbs: 'Glagoli i pridjevi', body: 'Tijelo', clothing: 'Odjeća',
    weather: 'Vrijeme', work: 'Posao i zanimanja', emotions: 'Emocije i osjećaji', house: 'Dom i kućanstvo', transport: 'Prijevoz',
    places: 'Grad i mjesta', shopping: 'Kupovina i trgovine', technology: 'Tehnologija', sport: 'Sport i hobiji', nature: 'Priroda i životinje',
    health: 'Zdravlje i medicina', education: 'Obrazovanje', finance: 'Novac i financije', restaurant: 'U restoranu',
    daily: 'Dnevna rutina', communication: 'Komunikacija', celebrations: 'Praznici i slavlja', countries: 'Zemlje i narodnosti',
    seasons: 'Godišnja doba i kalendar', adjectives: 'Pridjevi i suprotnosti', verbs2: 'Dodatni glagoli',
    kitchen: 'Kuhinja i kuhanje', materials: 'Materijali i alati', music: 'Glazba i umjetnost',
    law_society: 'Društvo i pravo', geography: 'Geografija i priroda', numbers2: 'Brojevi i matematika', character: 'Osobine karaktera',
    body2: 'Tijelo i izgled (nastavak)', animals2: 'Dodatne životinje', professions2: 'Dodatna zanimanja',
    house2: 'Dom (nastavak)', school2: 'Škola (nastavak)', travel2: 'Putovanja (nastavak)', environment: 'Vrijeme i okoliš',
    shapes: 'Oblici i mjere', computer2: 'Računala (nastavak)', religion: 'Religija i duhovnost', clothing2: 'Odjeća (nastavak)'
  },
  sr: {
    greetings: 'Поздрави', numbers: 'Бројеви', family: 'Породица', food: 'Храна', travel: 'Путовања',
    colors: 'Боје', time: 'Дани и време', verbs: 'Глаголи и придеви', body: 'Тело', clothing: 'Одећа',
    weather: 'Време', work: 'Посао и занимања', emotions: 'Емоције и осећања', house: 'Дом и домаћинство', transport: 'Превоз',
    places: 'Град и места', shopping: 'Куповина и продавнице', technology: 'Технологија', sport: 'Спорт и хобији', nature: 'Природа и животиње',
    health: 'Здравље и медицина', education: 'Образовање', finance: 'Новац и финансије', restaurant: 'У ресторану',
    daily: 'Дневна рутина', communication: 'Комуникација', celebrations: 'Празници и прославе', countries: 'Земље и националности',
    seasons: 'Годишња доба и календар', adjectives: 'Придеви и супротности', verbs2: 'Додатни глаголи',
    kitchen: 'Кухиња и кување', materials: 'Материјали и алати', music: 'Музика и уметност',
    law_society: 'Друштво и право', geography: 'Географија и природа', numbers2: 'Бројеви и математика', character: 'Особине карактера',
    body2: 'Тело и изглед (наставак)', animals2: 'Додатне животиње', professions2: 'Додатна занимања',
    house2: 'Дом (наставак)', school2: 'Школа (наставак)', travel2: 'Путовања (наставак)', environment: 'Време и животна средина',
    shapes: 'Облици и мере', computer2: 'Рачунари (наставак)', religion: 'Религија и духовност', clothing2: 'Одећа (наставак)'
  },
  el: {
    greetings: 'Χαιρετισμοί', numbers: 'Αριθμοί', family: 'Οικογένεια', food: 'Φαγητό', travel: 'Ταξίδια',
    colors: 'Χρώματα', time: 'Ημέρες και ώρα', verbs: 'Ρήματα και επίθετα', body: 'Σώμα', clothing: 'Ρούχα',
    weather: 'Καιρός', work: 'Δουλειά και επαγγέλματα', emotions: 'Συναισθήματα', house: 'Σπίτι και οικιακά', transport: 'Μεταφορές',
    places: 'Πόλη και μέρη', shopping: 'Ψώνια και καταστήματα', technology: 'Τεχνολογία', sport: 'Αθλητισμός και χόμπι', nature: 'Φύση και ζώα',
    health: 'Υγεία και ιατρική', education: 'Εκπαίδευση', finance: 'Χρήματα και οικονομικά', restaurant: 'Στο εστιατόριο',
    daily: 'Καθημερινή ρουτίνα', communication: 'Επικοινωνία', celebrations: 'Γιορτές και εορτασμοί', countries: 'Χώρες και εθνικότητες',
    seasons: 'Εποχές και ημερολόγιο', adjectives: 'Επίθετα και αντίθετα', verbs2: 'Περισσότερα ρήματα',
    kitchen: 'Κουζίνα και μαγειρική', materials: 'Υλικά και εργαλεία', music: 'Μουσική και τέχνη',
    law_society: 'Κοινωνία και δίκαιο', geography: 'Γεωγραφία και φύση', numbers2: 'Αριθμοί και μαθηματικά', character: 'Χαρακτηριστικά προσωπικότητας',
    body2: 'Σώμα και εμφάνιση (συνέχεια)', animals2: 'Περισσότερα ζώα', professions2: 'Περισσότερα επαγγέλματα',
    house2: 'Σπίτι (συνέχεια)', school2: 'Σχολείο (συνέχεια)', travel2: 'Ταξίδια (συνέχεια)', environment: 'Καιρός και περιβάλλον',
    shapes: 'Σχήματα και μετρήσεις', computer2: 'Υπολογιστές (συνέχεια)', religion: 'Θρησκεία και πνευματικότητα', clothing2: 'Ρούχα (συνέχεια)'
  },
  fi: {
    greetings: 'Tervehdykset', numbers: 'Numerot', family: 'Perhe', food: 'Ruoka', travel: 'Matkustaminen',
    colors: 'Värit', time: 'Päivät ja aika', verbs: 'Verbit ja adjektiivit', body: 'Keho', clothing: 'Vaatteet',
    weather: 'Sää', work: 'Työ ja ammatit', emotions: 'Tunteet', house: 'Koti ja kotitalous', transport: 'Liikenne',
    places: 'Kaupunki ja paikat', shopping: 'Ostokset ja kaupat', technology: 'Teknologia', sport: 'Urheilu ja harrastukset', nature: 'Luonto ja eläimet',
    health: 'Terveys ja lääketiede', education: 'Koulutus', finance: 'Raha ja talous', restaurant: 'Ravintolassa',
    daily: 'Päivärutiini', communication: 'Viestintä', celebrations: 'Juhlapyhät ja juhlat', countries: 'Maat ja kansallisuudet',
    seasons: 'Vuodenajat ja kalenteri', adjectives: 'Adjektiivit ja vastakohdat', verbs2: 'Lisää verbejä',
    kitchen: 'Keittiö ja ruoanlaitto', materials: 'Materiaalit ja työkalut', music: 'Musiikki ja taide',
    law_society: 'Yhteiskunta ja laki', geography: 'Maantiede ja luonto', numbers2: 'Numerot ja matematiikka', character: 'Luonteenpiirteet',
    body2: 'Keho ja ulkonäkö (lisää)', animals2: 'Lisää eläimiä', professions2: 'Lisää ammatteja',
    house2: 'Koti (lisää)', school2: 'Koulu (lisää)', travel2: 'Matkustaminen (lisää)', environment: 'Sää ja ympäristö',
    shapes: 'Muodot ja mitat', computer2: 'Tietokoneet (lisää)', religion: 'Uskonto ja henkisyys', clothing2: 'Vaatteet (lisää)'
  },
  hu: {
    greetings: 'Köszönések', numbers: 'Számok', family: 'Család', food: 'Étel', travel: 'Utazás',
    colors: 'Színek', time: 'Napok és idő', verbs: 'Igék és melléknevek', body: 'Test', clothing: 'Ruházat',
    weather: 'Időjárás', work: 'Munka és foglalkozások', emotions: 'Érzelmek', house: 'Otthon és háztartás', transport: 'Közlekedés',
    places: 'Város és helyek', shopping: 'Vásárlás és üzletek', technology: 'Technológia', sport: 'Sport és hobbi', nature: 'Természet és állatok',
    health: 'Egészség és orvoslás', education: 'Oktatás', finance: 'Pénz és pénzügyek', restaurant: 'Étteremben',
    daily: 'Napi rutin', communication: 'Kommunikáció', celebrations: 'Ünnepek és ünneplések', countries: 'Országok és nemzetiségek',
    seasons: 'Évszakok és naptár', adjectives: 'Melléknevek és ellentétek', verbs2: 'További igék',
    kitchen: 'Konyha és főzés', materials: 'Anyagok és eszközök', music: 'Zene és művészet',
    law_society: 'Társadalom és jog', geography: 'Földrajz és természet', numbers2: 'Számok és matematika', character: 'Jellemvonások',
    body2: 'Test és külső (folytatás)', animals2: 'További állatok', professions2: 'További foglalkozások',
    house2: 'Otthon (folytatás)', school2: 'Iskola (folytatás)', travel2: 'Utazás (folytatás)', environment: 'Időjárás és környezet',
    shapes: 'Alakzatok és mértékek', computer2: 'Számítógépek (folytatás)', religion: 'Vallás és spiritualitás', clothing2: 'Ruházat (folytatás)'
  }
};

App.ui = App.ui || {};
App.ui.categoryName = function (id, fallback) {
  const uiLang = (App.storage.getUILang && App.storage.getUILang()) || 'ru';
  const table = App.CATEGORY_NAMES[uiLang] || App.CATEGORY_NAMES.ru;
  return (table && table[id]) || (App.CATEGORY_NAMES.ru && App.CATEGORY_NAMES.ru[id]) || fallback || id;
};
